"""Generated by CMake. Tracks the latest requested Python wrapper build."""

WRAPPER_MODULE_PATH = r"/home/peterc/devDir/dev-tools/cpp_cuda_mathcore_for_cv/build/python/mathcore_for_cv/mathcore_for_cv.so"
WRAPPER_LIBRARY_DIRS = [r"/home/peterc/devDir/dev-tools/cpp_cuda_mathcore_for_cv/build/src"]
