"""Generated by CMake. Tracks the latest requested Python wrapper build."""

WRAPPER_MODULE_PATH = r"/home/peterc/devDir/MathCore_for_SpaceNav/build/python/mathcore_for_cv/mathcore_for_cv.so"
WRAPPER_LIBRARY_DIRS = [r"/home/peterc/devDir/MathCore_for_SpaceNav/build/src"]
