"""Generated by CMake. Tracks the latest requested Python wrapper build."""

WRAPPER_MODULE_PATH = r"/home/peterc/devDir/MathCore_for_SpaceNav/build/python/MathCore_for_SpaceNav/MathCore_for_SpaceNav.so"
WRAPPER_LIBRARY_DIRS = [r"/home/peterc/devDir/MathCore_for_SpaceNav/build/src"]
