[build-system]
requires = ["setuptools>=61", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "mathcore_for_cv"
version = "0.3.0"
description = "Python bindings for mathcore_for_cv."
requires-python = ">=3.12"
license = {text = "MIT"}
authors = [
  {name = "mathcore_for_cv contributors"}
]

[tool.setuptools]
packages = ["mathcore_for_cv"]
include-package-data = true

[tool.setuptools.package-data]
"mathcore_for_cv" = ["*.so", "*.pyd", "*.dylib", "*.pyi", "**/*.pyi"]
